[tool.poetry]
name = "framewise"
version = "0.1.0"
description = "AI-powered video tutorial assistant with intelligent frame extraction and multimodal RAG"
authors = ["Mohammad Esmaeili <your-email@example.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/yourusername/framewise"
repository = "https://github.com/yourusername/framewise"
keywords = ["video", "rag", "ai", "tutorials", "multimodal", "embeddings"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Multimedia :: Video",
]

[tool.poetry.dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 4b83543 (fix: Workaround for triton dependency on macOS)
python = "~3.11"
# Dependencies will be added incrementally
openai-whisper = "^20231117"
loguru = "^0.7.0"
opencv-python = "^4.8.0"
Pillow = "^10.0.0"
numpy = "^1.24.0"
<<<<<<< HEAD
<<<<<<< HEAD
sentence-transformers = "^2.2.2"
transformers = "^4.35.0"
lancedb = "^0.3.0"
anthropic = "^0.39.0"
python-dotenv = "^1.0.0"
langchain = "^0.3.0"
langchain-anthropic = "^0.3.0"
<<<<<<< HEAD
=======
>>>>>>> 4338149 (feat: Add intelligent frame extraction with scene detection)
=======
sentence-transformers = "^2.2.2"
transformers = "^4.35.0"
lancedb = "^0.3.0"
>>>>>>> 3dda9dd (feat: Add multimodal embeddings and vector search (Phase 3))
=======
>>>>>>> 25bbc40 (feat: Add transcript correction and complete LLM integration)

[tool.poetry.group.dev.dependencies]
# Dev dependencies will be added as needed
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"
=======
python = "^3.9"
=======
python = ">=3.9,<3.14"
>>>>>>> 6e8959a (feat: Add transcript extraction with Whisper)
# Dependencies will be added incrementally
openai-whisper = "^20231117"
loguru = "^0.7.0"

[tool.poetry.group.dev.dependencies]
# Dev dependencies will be added as needed
<<<<<<< HEAD
>>>>>>> db3361e (Initial commit: Project structure and Poetry setup)
=======
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"
>>>>>>> 6e8959a (feat: Add transcript extraction with Whisper)

[tool.poetry.scripts]
framewise = "framewise.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py39', 'py310', 'py311']

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
